org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=createsimpleschematic
mod_name=Create: Simple Schematic
mod_license=MIT
mod_version=1.2.0-for-create-0.5.1
mod_group_id=com.leaf.createsimpleschematic
mod_authors=Apertyotis, Leaf
mod_description=\
  This mod extracts and port the "Simple Schematic" feature from [Create: Andesite Abound] into a fully standalone package.

mc_version=1.20.1
jei_version=15.2.0.27

create_minecraft_version = 1.20.1
flywheel_minecraft_version = 1.20.1
create_version = 0.5.1.j-55
flywheel_version = 0.6.11-13
registrate_version = MC1.20-1.3.3